### PR TITLE
Remove scanner.cc

### PR DESCRIPTION
**Pull request by aibaars**
I don't think we need a hand-crafted scanner for ERB files. Tree-sitter's rules for handling [Conflicting tokens](https://tree-sitter.github.io/tree-sitter/creating-parsers#conflicting-tokens) make sure that tokens like `%>`, `<%`, `<%=`, etc. take precedence over single character `%`, `>`, `<`, `=`, etc.

@maxbrunsfeld

### CODE REVIEW

**Review by maxbrunsfeld — APPROVED** [review]
Ha, great point. I'm not sure why I didn't think of using this technique.

**Comment by aibaars** [comment]
@maxbrunsfeld I rebased this to resolve conflicts in `parser.c` and `scanner.cc` introduced by my earlier pull requests. Could you have a quick look at this again and merge if you're happy?

**Comment by maxbrunsfeld** [comment]
I believe you also need to remove any reference to `scanner.cc` in the rust binding's `build.rs` file.

**Comment by aibaars** [comment]
> I believe you also need to remove any reference to `scanner.cc` in the rust binding's `build.rs` file.

Well spotted, thanks!

I updated the Rust files

**Pull request merged**
